"""empty message

Revision ID: 7295b3c224e4
Revises: 4360cc29b3c7
Create Date: 2022-08-21 00:26:41.216370

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7295b3c224e4'
down_revision = '4360cc29b3c7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Artist', sa.Column('looking_for_venue', sa.Boolean(), nullable=True))
    op.drop_column('Artist', 'is_looking_for_venue')
    op.add_column('Venue', sa.Column('seeking_talent', sa.Boolean(), nullable=True))
    op.drop_column('Venue', 'is_seeking_talent')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Venue', sa.Column('is_seeking_talent', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_column('Venue', 'seeking_talent')
    op.add_column('Artist', sa.Column('is_looking_for_venue', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_column('Artist', 'looking_for_venue')
    # ### end Alembic commands ###
